### ISSUE TITLE
Error running snakemake

### ISSUE THREAD

**Issue by justinesjw** [gustaveroussy/sopa#10]
Hello!

Thank you for generating sopa! 

I am trying to run snakemake on a toy dataset. I manage to set up the environment to run snakemake but failed for both baysor and cellpose.

Here is a snapshot of an error message for cellpose cell segmentation 
![image](https://github.com/gustaveroussy/sopa/assets/26448066/911ba915-ab08-4a34-9d33-c52965dc33a4)

and here is the error message for baysor
![image](https://github.com/gustaveroussy/sopa/assets/26448066/57488fa8-b49e-4125-a313-15b4d2c43beb)

Both errors seem to be related to `patchify`.
I am very new in running snakemake pipelines, could you please give me some clue to understand these outputs?

Thanks, 
Justine

**Comment by quentinblampey** [comment]
Hello @justinesjw!

I worked on some updates on Monday and Tuesday to release a new version (`1.0.1`), and I think you cloned the repository between the changes. I'm sorry for that, I will update the doc so that Snakemake users clone the repository from a stable version instead of the `master` branch.

I will release version `1.0.1` in a few hours, I'll let you know!

**Comment by quentinblampey** [comment]
I just released version `1.0.1`!

Actually, for snakemake, I think the best way would be to install sopa in dev mode: this will prevent the kind of issue you experienced here.
Therefore, I updated the documentation, see [here](https://gustaveroussy.github.io/sopa/getting_started/#snakemake-setup) the new installation guide for snakemake. In brief: clone again the repository (or just run `git pull`) to get the latest updates, delete your old environment, and follow the new installation instructions.

Sorry again for this issue, let me know if it's fixed :)

PS: Btw, the toy dataset tutorial is now [here](https://gustaveroussy.github.io/sopa/tutorials/snakemake/#toy-example)
PS': the API tutorial is coming soon, probably by the end of the week

**Comment by justinesjw** [comment]
Thank you so much for the clear explanation! I have successfully implemented it for cellpose! 
However, I still face error with Baysor with this error 

![image](https://github.com/gustaveroussy/sopa/assets/26448066/f5b2ac7f-71c2-4b54-97bc-a6639920156b)

According to this [issue](https://github.com/JuliaLang/PackageCompiler.jl/issues/738#issuecomment-1838901893), is it a problem when using julia on mac. The [solution that I found there](https://gist.github.com/terasakisatoshi/c1b03c8b2791340b33e6781038e1c451) hint to add some code before compiling a package but I can't seem to figure out where or how to implement the solution. 

Do you by any chance how can I solve this? If not, I will update you when I figure it out :) 

Thanks again!

**Comment by quentinblampey** [comment]
Good to hear that Cellpose now works for you!

I have a mac too and my Baysor installation went well, so it's definitely possible to make it work. Have you used the binary download or the "Install as a Julia Package" option? (https://github.com/kharchenkolab/Baysor/#Installation)
For me, the second option worked well. If it still doesn't work I guess you can open an issue on the Baysor repository, since this issue is only related to Baysor :)

**Comment by quentinblampey** [comment]
Hello @justinesjw, were you able to fix this issue?
Since this is Baysor-related, I'll close the issue, but feel free to re-open if needed!
